### PR TITLE
Submit MusicBrainz tags to ListenBrainz scrobbles

### PR DESCRIPTION
**Pull request by staticssleever668**

### CODE REVIEW

**Comment by staticssleever668** [comment]
By the way, it seems like even when you rescan songs, be it from the "Rescan song(s)..." item in the context menu, or "Do a full collection rescan", the newly supported MusicBrainz tags from a35146440c2733d4626a5ce640e4ff90fef5884d don't get added to songs already in the database.
For testing I just copied a random song that has such metadata to another location, and opened it through Strawberry.

---

I am not sure if the order of listens stays intact, but you can see a listen submitted with this patch here: https://listenbrainz.org/user/waggery_assonant/?min_ts=1679697078
See a listen of White Surf Style 6 by OMORI submitted on 2023-03-25 12:33:24 UTC.

**Comment by jonaski** [comment]
Thanks, but I was already working on this, commited now https://github.com/strawberrymusicplayer/strawberry/commit/fab38f693d6b336520ae20bedb910d18e5df94c0
Maybe you can look over and see if I missed anything.

**Comment by jonaski** [comment]
> By the way, it seems like even when you rescan songs, be it from the "Rescan song(s)..." item in the context menu, or "Do a full collection rescan", the newly supported MusicBrainz tags from [a351464](https://github.com/strawberrymusicplayer/strawberry/commit/a35146440c2733d4626a5ce640e4ff90fef5884d) don't get added to songs already in the database. For testing I just copied a random song that has such metadata to another location, and opened it through Strawberry.
> 

Try with this https://github.com/strawberrymusicplayer/strawberry/commit/ed260c6e208fcaf3731197da849395a47ac0ee5e

**Comment by staticssleever668** [comment]
> Thanks, but I was already working on this, commited now [fab38f6](https://github.com/strawberrymusicplayer/strawberry/commit/fab38f693d6b336520ae20bedb910d18e5df94c0) Maybe you can look over and see if I missed anything.

https://github.com/strawberrymusicplayer/strawberry/blob/fab38f693d6b336520ae20bedb910d18e5df94c0/src/scrobbler/listenbrainzscrobbler.cpp#L451-L459
I don't think you need to submit *all* of them, especially if musicbrainz_artist_id and musicbrainz_album_artist_id have the same ID.
Maybe prefer musicbrainz_artist_id over musicbrainz_album_artist_id over musicbrainz_original_artist_id? (in my PR there is no fall back at all).
Otherwise looks good to me!

**Comment by staticssleever668** [comment]
@jonaski 

> Try with this [ed260c6](https://github.com/strawberrymusicplayer/strawberry/commit/ed260c6e208fcaf3731197da849395a47ac0ee5e)

It doesn't seem to work with "Rescan song(s)". If I also modify song title, for example, only then it updates the song.
To clarify, I have a collection full of songs tagged with MusicBrainz tags already, and I have been listening with previous version of Strawberry for a while. The files themselves didn't change, it's just that Strawberry doesn't reread the same songs just to use the newly supported MusicBrainz tags.
Let me try if a full collection scan would work...

**Comment by staticssleever668** [comment]
The full collection just completed - it doesn't work with it either.

**Comment by staticssleever668** [comment]
> The full collection just completed - it doesn't work with it either.

Never mind, I just happened to test it with an album that did not have MetaBrainz tags, oops. :persevere: 

Still, it doesn't work with "Rescan song(s)...".

**Comment by jonaski** [comment]
Found a bug: https://github.com/strawberrymusicplayer/strawberry/commit/4de912cf4133931156e0e3b7a452e91659532ebd

**Comment by jonaski** [comment]
> > The full collection just completed - it doesn't work with it either.
> 
> Never mind, I just happened to test it with an album that did not have MetaBrainz tags, oops. persevere Still, it doesn't work with "Rescan song(s)...". All tracks have updated, which also means I won't be able to test it anymore, sorry.

The rescan songs feature has always been flawed in many ways, it wasn't ignoring mtime, so unless the files were actually changed, it wasn't doing anything, should be fixed now I think.

**Pull request closed without merging**
