### PR TITLE
Italian language update

### PR DESCRIPTION
**Pull request by bovirus**
@jonaski 

Please check and merge. Thanks.

### CODE REVIEW

**Comment by jonaski** [comment]
This needs to go through Zanata: https://wiki.strawberrymusicplayer.org/wiki/How_to_translate

**Comment by bovirus** [comment]
@jonaski

I din't see this ifno in any place.

Coudl be useful to post this important info in your githome page and in your site.

**Comment by jonaski** [comment]
It's a bit hidden. Do you have this option? If not I can import it for you.

image

**Comment by bovirus** [comment]
@jonaski 

Thanks a lot.
I found it only when you explain.
Is not so visible.

But uplaod seems not works as expected (nothing changed) ort I didn't have the rioght to do it.

The full translation is here.

https://mega.nz/file/rRxgzYIJ#zOWeE39ILj4bj10sbN08RCBXG31NLuZwpwzaHG-8MmU

Please upload it.

**Pull request closed without merging**
